### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by trees-smoke** [boramalper/deima#1]
When I try to upload a file I get the following,
index.js:24 Uncaught (in promise) TypeError: Cannot read property 'Buffer' of undefined
    at FileReader.reader.onload (index.js:24)

**Comment by Katamori** [comment]
Same here.

**Comment by boramalper** [comment]
I am shutting down the repo as it is built on a grave misunderstanding (I did not realise that someone had to "pin" the files for gateways to keep serving them).

Your issue is valid, but no longer relevant. Sorry!
