### ISSUE TITLE
How to keep images online

### ISSUE THREAD

**Issue by kivutar** [boramalper/deima#2]
This is very nice but how are you going to keep the images online?

If nobody ever pins it, who will resolve it after a few hours?

**Comment by boramalper** [comment]
Sorry for the belated reply.

You are absolutely right, I did not realise that IPFS is not a free NAS where you can "dump" things... =) 

I've reflected upon my experience here [What IPFS Fails to Address?](https://blog.boramalper.org/what-ipfs-fails-to-address/).

I'll make the repo read-only and put a clear announcement that it doesn't work as intended/advertised.

Thank you!
